site_name: Gensokyo Reimagined Wiki
nav:
    - Home: index.md
    - FAQ: faq.md
    - Features: overview/features.md
    - Rules: 
      - Rules Overview: rules/rules.md
      - Moderation Decisions: 
        - Decisions Overview: rules/moderationdecisions.md
        - Grief: rules/grief.md
        - Harrasment:
          - Excessive PVP: rules/excessivepvp.md
          - Disrespecting Others: rules/disrespectingothers.md
        - Hacking: rules/hacking.md
        - Exploit Abuse: rules/exploitabuse.md
        - Chat:
          - Excessive swearing/hate speech: rules/Swear&Hate.md
          - Spam: rules/spam.md
        - Ban Circumvention: rules/bancircumvention.md
    - Server Guide:
      - Resources:
        - Fishing Resources: server-guide/fishing-resources.md
        - Crop Resources: server-guide/crop-resources.md
        - Drop Resources: server-guide/drop-resources.md
      - Mobs:
        - Wildlife Mobs: server-guide/wildlife-mobs.md
        - Touhou Mobs: server-guide/touhou-mobs.md
        - Bosses: server-guide/bosses.md
      - Starting Out: server-guide/starting-out.md
      - Classes, skills and attributes: server-guide/classes-skills.md
      - Getting Money: server-guide/money.md
      - Ore Rates: server-guide/ore-rates.md


theme:
  name: material
  favicon: overrides/assets/icon.png
  logo: overrides/assets/icon.png
  language: en
  icon:
    admonition:
      <type>: material/pencil 
  features:
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - abbr
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
plugins:
  - mkdocs-video
  - search:                                         
      lang: en 
  - i18n:
      default_language: en
      docs_structure: folder
      languages:
        en:
          name: English
          link: ./en/
          build: true
        fr:
          name: Français
          link: ./fr/
          build: true
extra:
  alternate:
    - name: English
      link: ./en/ 
      lang: en
    - name: Français
      link: ./fr/
      lang: fr

